In [15]:
import  numpy as np

In [16]:
a = np.arange(0,18)
b = np.arange(20,38)
print(a)
print(b)
print(a+b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54]


In [22]:
c= a.reshape(3,6)
d= b.reshape(3,6)
print(c)
print(d)
print(c+d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[20 21 22 23 24 25]
 [26 27 28 29 30 31]
 [32 33 34 35 36 37]]
[[20 22 24 26 28 30]
 [32 34 36 38 40 42]
 [44 46 48 50 52 54]]
