In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
lst = np.array([1,2,3,4,5,6])
print(lst)

[1 2 3 4 5 6]


In [9]:
oneD= np.array([1,2,3])
print(oneD)

[1 2 3]


In [10]:
twoD= np.array([[1,2,3],[4,5,6]])
print(twoD)
print(twoD[1,2])

[[1 2 3]
 [4 5 6]]
6


In [19]:
threeD = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9],[10,11,12]],
                   [[13,14,15],[16,17,18]]
                   ])
print(threeD)

print(threeD[0,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
5
