In [2]:
import numpy as np

In [15]:
tow_d = np.array([[1,2,3],[4,5,6]])
print(tow_d)



def transpose(matrix):
    row ,col = len(matrix), len(matrix[0])
    ans= [[0]*row for _ in range(col)]
    for i in range(row):
        for j in range(col):
            ans[j][i]=matrix[i][j]
    return ans

transpose_matrix = transpose(tow_d)
print("transpose matrix:")
print(transpose_matrix)

print("transpose matrix using build in :")

print(tow_d.T)


[[1 2 3]
 [4 5 6]]
transpose matrix:
[[np.int64(1), np.int64(4)], [np.int64(2), np.int64(5)], [np.int64(3), np.int64(6)]]
transpose matrix using build in :
[[1 4]
 [2 5]
 [3 6]]


In [20]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])

sum = A[0,1]+ B[1,0]  #2+10

print("Sum of elements at (0,1) and (1,0) of matrix A and B is:", sum)

print("Sum of elements of matrix A and B is:", np.sum(A+B))  # 58

diff = B[1,2]- A[0,1]
print(diff)

Sum of elements at (0,1) and (1,0) of matrix A and B is: 12
Sum of elements of matrix A and B is: 78
10
