In [1]:
import numpy as np 

In [2]:
test = np.ones(4)
print(test)

[1. 1. 1. 1.]


In [3]:
test = np.ones(int(5), dtype=int)
print(test)

[1 1 1 1 1]


In [4]:
z= np.zeros((3,4),dtype=int)
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
arr= np.arange(1,25,2)
print(arr)
ar1= np.linspace(0,5,5)
print(ar1)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
[0.   1.25 2.5  3.75 5.  ]


In [6]:
matrix_arr= arr.reshape(4,3)
print(matrix_arr)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


In [7]:
a = np.arange(0,18)
b = np.arange(20,38)
print(a)
print(b)
print(a+b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54]


In [8]:
r_a = a.reshape(3,6)
r_b = b.reshape(3,6)
print(r_a+r_b)

[[20 22 24 26 28 30]
 [32 34 36 38 40 42]
 [44 46 48 50 52 54]]


In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = np.dot(A, B)  # or A @ B
print("Matrix Multiplication:\n", C)


Matrix Multiplication:
 [[19 22]
 [43 50]]
